repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: loki-stack
    namespace: monitoring
    chart: grafana/loki-stack
    version: 2.9.11
    values:
      -  ../helm_chart/loki-values.yaml