hooks:
  - events: ["prepare"]
    showlogs: true
    command: kubectl
    args: ["apply", "-f", "../helm_chart/templates/ns.yaml"]

releases:
  - name: django-app
    namespace: django-app
    createNamespace: false
    chart: ../helm_chart
    values:
      - ../helm_chart/values.yaml
