apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "project.name" .}}
  namespace: {{ include "project.name" .}}
  labels:
    app: {{ include "project.name" .}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "project.name" .}}
  template:
    metadata:
      labels: 
        app: {{ include "project.name" .}}
    spec:
      containers:
      - name: {{ include "project.name" .}}
        image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.containerPort }} 

        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: {{ include "project.name" .}}-secret
                key: db-url
          - name: DJANGO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "project.name" .}}-secret
                key: password
          - name: DJANGO_ALLOWED_HOSTS
            valueFrom:
              configMapKeyRef:
                name: config
                key: allowed-hosts
          - name: DEBUG
            valueFrom:
              configMapKeyRef:
                name: config
                key: debug

        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10

        # securityContext:
        #   runAsNonRoot: true
        #   runAsUser: 1000
        #   readOnlyRootFilesystem: true
        #   allowPrivilegeEscalation: false
