# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: delete-ingress-nginx-validatingwebhook
#   annotations:
#     "helm.sh/hook": post-install,post-upgrade
#     "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
# spec:
#   template:
#     spec:
#       containers:
#         - name: kubectl
#           image: bitnami/kubectl:latest
#           command: ["kubectl", "delete", "ValidatingWebhookConfiguration", "ingress-nginx-admission"]
#       restartPolicy: Never
