apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "project.name" .}}-network-policies
  namespace: {{ include "project.name" .}}
spec:
  podSelector:
    matchLabels:
      app:  {{ include "project.name" .}}
  policyTypes:
  - Ingress
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 5432
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: 8000
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 5432
   