apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "project.name" .}}-deployment-role
  namespace: {{ include "project.name" .}}
  labels:
    role-group: dev
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "create", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "project.name" .}}-service-role
  namespace: {{ include "project.name" .}}
  labels:
    role-group: dev
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "create", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "project.name" .}}-logs-role
  namespace: {{ include "project.name" .}}
  labels:
    role-group: dev
rules:
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "project.name" .}}-aggregated-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      role-group: dev

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "project.name" .}}-team-binding
subjects:
- kind: User
  name: Bobby
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: {{ include "project.name" .}}-aggregated-role
  apiGroup: rbac.authorization.k8s.io